name: GeneticChickengineering
author: kiichan, ybw0014, wickidcow
description: Resource chickens for Slimefun Legacy on modern Paper-family servers.
main: net.guizhanss.gcereborn.GeneticChickengineering
website: https://github.com/wickidcow/SF_GeneticChickEngineering
version: ${project.version}
api-version: '1.21'
folia-supported: true
depend:
  - Slimefun
softdepend:
  - StackMob
  - WildStacker
commands:
  geneticchickengineering:
    aliases: gce
    description: GCE base command
    usage: "Usage: /<command> <subcommand> [arguments]"
permissions:
  geneticchickengineering.command.makechicken:
    description: Allows a player to make Pocket Chickens from command
    default: op
  geneticchickengineering.command.calcchance:
    description: Allows a player to calculate the chances of getting a specific offspring from two parents
    default: true
